### ISSUE TITLE
`bats-file`, `bats-detik`, `bats-support` not available via Homebrew

### ISSUE THREAD

**Issue by jwheeler31** [bats-core/homebrew-bats-core#3]
Following the installation instructions from scratch (c/o @MichaelDimmitt), `bats-file`, `bats-detik`, and `bats-support` are missing from Homebrew. `kaos/shell` provides `bats-file` and `bats-support` - is that the intended functionality?

**Comment by MichaelDimmitt** [comment]
will be adding them this weekend

**Comment by brokenpip3** [comment]
@martin-schulze-vireso we can close this afaik

**Comment by MichaelDimmitt** [comment]
@jwheeler31 , the pr has been merged can you test installing the homebrews and get back about the results ?

**Comment by jwheeler31** [comment]
Everything looks good - ran `brew install bats-file bats-detik bats-support` successfully.

**Comment by kief** [comment]
As far as I can see, these aren't available with the default taps:

```
$ brew install bats-file bats-detik bats-support
Warning: No available formula with the name "bats-file". Did you mean bats-core?
==> Searching for similarly named formulae...
This similarly named formula was found:
bats-core ✔
To install it, run:
  brew install bats-core ✔
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```
